name = "forge-dashboard"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "dae540d1c9880eb0d8fe720705f05080"

[vars]
DASHBOARD_VERSION = "2.0.0"
API_TOKEN = "forge-dashboard-api-2026"

[[kv_namespaces]]
binding = "STATE"
id = "3af8f68987954907a20835f33a100305"
