function renderCssDeclarations(tokens) {
  return Object.entries(tokens)
    .map(([name, value]) => `      ${name}: ${value};`)
    .join('\n');
}

const sharedTokenDefaults = {
  '--shell-max-width': '1520px',
  '--shell-padding': '24px 24px 40px',
  '--shell-min-height': 'auto',
  '--shell-display': 'block',
  '--shell-grid-template-rows': 'none',
  '--shell-align-content': 'normal',
  '--shell-gap': 'normal',
  '--shell-overflow': 'visible',
  '--shell-text-primary': '#f4f8fc',
  '--shell-text-secondary': '#a7b8cc',
  '--shell-text-tertiary': '#6e849d',
  '--shell-border': 'rgba(164, 188, 214, 0.14)',
  '--shell-border-strong': 'rgba(164, 188, 214, 0.24)',
  '--shell-accent': '#6ab3ff',
  '--shell-accent-strong': '#95ceff',
  '--shell-brand-kicker-color': 'var(--shell-accent-strong)',
  '--shell-nav-text': 'var(--shell-text-secondary)',
  '--shell-nav-active-text': 'var(--shell-text-primary)',
  '--shell-nav-active-start': 'rgba(106, 179, 255, 0.2)',
  '--shell-nav-active-end': 'rgba(255, 138, 45, 0.12)',
  '--shell-nav-active-border': 'rgba(149, 206, 255, 0.18)',
  '--shell-topbar-margin': '14px',
  '--shell-topbar-separator': '0 1px 0 rgba(106, 179, 255, 0.06)',
  '--shell-topbar-haze-inset': '-28% -6% auto',
  '--shell-topbar-haze-height': '140%',
  '--shell-nav-gap': '8px',
  '--shell-nav-padding': '6px',
  '--shell-nav-link-gap': '9px',
  '--shell-nav-link-padding': '11px 16px',
  '--shell-nav-link-font-size': '14px',
  '--shell-brand-title-size': '18px',
  '--shell-brand-title-spacing': '-0.03em',
  '--shell-meta-gap': '12px',
  '--shell-heartbeat-width': '160px',
  '--shell-heartbeat-height': '38px',
  '--shell-heartbeat-columns': 'repeat(20, minmax(0, 1fr))',
  '--shell-heartbeat-gap': '3px',
  '--shell-heartbeat-padding': '7px 10px',
  '--shell-heartbeat-border': '1px solid var(--shell-chip-border)',
  '--shell-heartbeat-bg': 'rgba(255,255,255,0.03)',
  '--shell-heartbeat-radius': '999px',
  '--shell-heartbeat-align': 'stretch',
  '--shell-heartbeat-bar-bg': 'linear-gradient(180deg, rgba(255,255,255,0.12), rgba(255,255,255,0.02))',
  '--shell-heartbeat-bar-height': '100%',
  '--shell-heartbeat-bar-opacity': '1',
  '--shell-heartbeat-origin': 'bottom center',
  '--shell-heartbeat-duration': '1.7s',
  '--shell-heartbeat-delay-step': '70ms',
  '--shell-heartbeat-active-bg': 'linear-gradient(180deg, rgba(105, 200, 255, 0.95), rgba(255, 138, 45, 0.5))',
  '--shell-heartbeat-active-shadow': '0 0 14px rgba(105, 200, 255, 0.16)',
  '--shell-heartbeat-blocked-bg': 'linear-gradient(180deg, rgba(255, 177, 68, 0.95), rgba(255, 107, 122, 0.52))',
  '--shell-heartbeat-blocked-shadow': '0 0 14px rgba(255, 107, 122, 0.16)',
  '--shell-chip-padding': '10px 14px',
  '--shell-chip-border': '1px solid var(--shell-border)',
  '--shell-chip-bg': 'rgba(255,255,255,0.03)',
  '--shell-chip-font-size': '13px',
  '--shell-chip-text': 'var(--shell-text-secondary)',
  '--shell-chip-strong': 'var(--shell-text-primary)',
  '--shell-clock-font-family': '"IBM Plex Mono", ui-monospace, monospace',
  '--component-button-bg': 'rgba(255,255,255,0.04)',
  '--component-button-border': '1px solid var(--shell-border)',
  '--component-button-text': 'var(--shell-text-primary)',
  '--component-button-hover-bg': 'rgba(106, 179, 255, 0.08)',
  '--component-button-hover-border': 'rgba(149, 206, 255, 0.22)',
  '--component-button-primary-start': 'rgba(106, 179, 255, 0.2)',
  '--component-button-primary-end': 'rgba(255, 138, 45, 0.12)',
  '--component-button-primary-border': 'rgba(149, 206, 255, 0.2)',
  '--component-section-padding': '20px',
  '--component-section-radius': '24px',
  '--component-section-bg': 'rgba(11, 20, 31, 0.88)',
  '--component-section-border': '1px solid var(--shell-border)',
  '--component-section-shadow': '0 12px 36px rgba(0, 0, 0, 0.22)',
  '--component-section-title-size': '22px',
  '--component-section-title-spacing': '-0.04em',
  '--component-section-subtle-color': 'var(--shell-text-tertiary)',
  '--component-metric-padding': '18px',
  '--component-metric-radius': '18px',
  '--component-metric-bg': 'rgba(10, 18, 28, 0.84)',
  '--component-metric-border': '1px solid var(--shell-border)',
  '--component-metric-shadow': '0 14px 40px rgba(0, 0, 0, 0.24)',
  '--component-metric-value-size': '42px',
  '--component-metric-label-color': 'var(--shell-text-tertiary)',
  '--component-metric-copy-color': 'var(--shell-text-secondary)',
  '--component-metrics-gap': '16px',
  '--component-metrics-margin-top': '0px',
  '--component-metrics-margin-bottom': '18px',
  '--component-pill-bg': 'rgba(255,255,255,0.05)',
  '--component-pill-border': '1px solid rgba(255,255,255,0.05)',
  '--component-pill-text': 'var(--shell-text-secondary)',
};

const compactTokenOverrides = {
  '--shell-brand-kicker-color': 'var(--blue)',
  '--shell-nav-text': 'var(--muted)',
  '--shell-nav-active-start': 'rgba(121, 188, 255, 0.18)',
  '--shell-nav-active-end': 'rgba(255, 158, 82, 0.12)',
  '--shell-nav-active-border': 'rgba(255,255,255,0.08)',
  '--shell-nav-gap': '10px',
  '--shell-nav-link-gap': '8px',
  '--shell-nav-link-padding': '10px 14px',
  '--shell-nav-link-font-size': '13px',
  '--shell-brand-title-size': '24px',
  '--shell-brand-title-spacing': '-0.05em',
  '--shell-heartbeat-width': '132px',
  '--shell-heartbeat-height': '28px',
  '--shell-heartbeat-columns': 'repeat(18, minmax(0, 1fr))',
  '--shell-heartbeat-gap': '4px',
  '--shell-heartbeat-padding': '0px',
  '--shell-heartbeat-border': 'none',
  '--shell-heartbeat-bg': 'transparent',
  '--shell-heartbeat-align': 'end',
  '--shell-heartbeat-bar-bg': 'linear-gradient(180deg, rgba(121, 188, 255, 0.96), rgba(255, 158, 82, 0.62))',
  '--shell-heartbeat-bar-height': '26%',
  '--shell-heartbeat-bar-opacity': '0.46',
  '--shell-heartbeat-origin': 'center bottom',
  '--shell-heartbeat-duration': '1.8s',
  '--shell-heartbeat-delay-step': '90ms',
  '--shell-chip-padding': '10px 12px',
  '--shell-chip-border': '1px solid rgba(255,255,255,0.05)',
  '--shell-chip-text': 'var(--muted)',
  '--component-button-text': 'var(--text)',
  '--component-section-bg': 'var(--panel-2)',
  '--component-section-radius': 'var(--radius)',
  '--component-section-shadow': '0 20px 54px rgba(0, 0, 0, 0.24)',
  '--component-section-subtle-color': 'var(--soft)',
  '--component-metric-padding': '20px',
  '--component-metric-radius': 'var(--radius-md)',
  '--component-metric-bg': 'var(--panel-2)',
  '--component-metric-shadow': '0 16px 38px rgba(0, 0, 0, 0.22)',
  '--component-metric-value-size': '42px',
  '--component-metric-label-color': 'var(--soft)',
  '--component-metric-copy-color': 'var(--muted)',
  '--component-metrics-margin-top': '28px',
  '--component-metrics-margin-bottom': '0px',
  '--component-pill-text': 'var(--muted)',
};

const reviewTokenOverrides = {
  '--shell-padding': '16px 18px 18px',
  '--shell-min-height': '100vh',
  '--shell-display': 'grid',
  '--shell-grid-template-rows': 'auto auto auto',
  '--shell-align-content': 'start',
  '--shell-gap': '12px',
  '--shell-text-primary': '#f3f7fb',
  '--shell-text-secondary': '#9cb1c8',
  '--shell-text-tertiary': '#6d8297',
  '--shell-accent': '#69a7ff',
  '--shell-accent-strong': '#69a7ff',
  '--shell-topbar-margin': '0px',
};

export function renderStandardTokenDeclarations(overrides = {}) {
  return renderCssDeclarations({
    ...sharedTokenDefaults,
    ...overrides,
  });
}

export function renderCompactTokenDeclarations(overrides = {}) {
  return renderStandardTokenDeclarations({
    ...compactTokenOverrides,
    ...overrides,
  });
}

export function renderReviewTokenDeclarations(overrides = {}) {
  return renderStandardTokenDeclarations({
    ...reviewTokenOverrides,
    ...overrides,
  });
}
